export const MOD_NODEJS = {
  id: 'node',
  title: 'Node.js & Eng. Reversa HTTP',
  steps: [
    {
      short: '1. socket() e bind()',
      title: '🔧 Socket, Bind e Listen: O Nascimento do Servidor',
      content: '<p>Quando seu script executa <code>app.listen(3000)</code>, o JavaScript não toca a rede diretamente. O Engine <strong>V8</strong> delega para o <strong>TCPWrap</strong>, um binding C++ que faz a ponte entre JS e a <strong>libuv</strong> (biblioteca C de I/O assíncrono). A libuv então invoca as <em>syscalls</em> do kernel Linux:</p><div class="code-block">// 1. Criar o socket (File Descriptor)\nint fd = socket(AF_INET, SOCK_STREAM, 0);\n→ fd = 3  (primeiro FD disponível após stdin=0, stdout=1, stderr=2)\n\n// AF_INET    = Address Family IPv4 (AF_INET6 para IPv6)\n// SOCK_STREAM = TCP (orientado a conexão, stream de bytes)\n//               SOCK_DGRAM seria UDP (datagramas)\n// 0          = Protocolo padrão (TCP para STREAM, UDP para DGRAM)</div><p>Em Unix, <strong>tudo é um arquivo</strong>. O socket retorna um <strong>File Descriptor (fd)</strong> — um inteiro que identifica o recurso no kernel. Esse fd é a "referência" que será usada em todas as operações subsequentes (bind, listen, accept, read, write, close).</p><div class="code-block">// 2. Vincular o socket a um endereço:porta\nsetsockopt(fd, SOL_SOCKET, SO_REUSEADDR, 1);  // Reusar porta após crash\nbind(fd, {sa_family=AF_INET, sin_port=htons(3000), sin_addr=0.0.0.0}, 16);\n→ return 0 (sucesso)\n\n// sin_addr=0.0.0.0 = escuta em TODAS as interfaces (eth0, lo, wlan0)\n// sin_addr=127.0.0.1 = escuta apenas em localhost\n// htons() = Host TO Network Short (converte endianness)\n\n// 3. Marcar como servidor (modo passivo)\nlisten(fd, backlog=511);\n→ O kernel cria duas filas:\n   • SYN Queue (half-open): conexões no meio do handshake\n   • Accept Queue (completed): conexões prontas para accept()</div><p>O <strong>backlog</strong> (padrão 511 no Node.js) define o tamanho máximo da Accept Queue — quantas conexões completamente handshaked podem esperar antes de serem aceitas pelo processo. Se a fila estourar, o kernel descarta SYNs novos (o cliente recebe timeout). Em servidores de alto tráfego, tunar <code>net.core.somaxconn</code> e o backlog é crítico.</p><p><code>SO_REUSEADDR</code> permite reusar a porta imediatamente após o processo terminar, sem esperar o estado TIME_WAIT expirar (~60s). Sem essa flag, reiniciar o servidor rapidamente daria <code>EADDRINUSE</code>.</p>',
      refs: [
        {text: 'man 2 socket (Linux)', url: 'https://man7.org/linux/man-pages/man2/socket.2.html'},
        {text: 'man 2 listen (Linux)', url: 'https://man7.org/linux/man-pages/man2/listen.2.html'}
      ]
    },
    {
      short: '2. epoll & Event Loop',
      title: '⚡ O Event Loop: epoll e as Fases da libuv',
      content: '<p>Servidores tradicionais (Apache, PHP-FPM) criam <strong>1 thread por conexão</strong>, cada uma consumindo ~2MB de stack. Com 10.000 conexões simultâneas = 20GB de RAM só em threads. O Node.js resolve isso com uma <strong>única thread principal</strong> e o mecanismo de I/O assíncrono do kernel: o <span class="highlight">epoll</span>.</p><div class="code-block">// A libuv registra o fd do servidor no epoll:\nepoll_create1(0);           → epfd = 4 (File Descriptor do epoll)\nepoll_ctl(epfd, EPOLL_CTL_ADD, fd=3, {EPOLLIN});\n// "Kernel: me avise quando o fd 3 tiver dados para ler"\n\n// Main thread entra em espera eficiente:\nepoll_wait(epfd, events[], maxevents, timeout);\n// → Thread DORME (não consome CPU)\n// → Kernel ACORDA a thread quando hardware gera interrupt</div><p>O <strong>Event Loop</strong> da libuv executa em ciclos contínuos com <strong>6 fases ordenadas</strong>:</p><div class="code-block">┌───────────────────────────┐\n│    ① Timers               │  setTimeout, setInterval\n│    (callbacks expirados)  │  (verifica heap de timers)\n├───────────────────────────┤\n│    ② Pending Callbacks    │  Callbacks de I/O adiados\n│    (erros TCP, etc.)      │  do ciclo anterior\n├───────────────────────────┤\n│    ③ Idle / Prepare       │  Uso interno da libuv\n│    (setup para poll)      │\n├───────────────────────────┤\n│    ④ Poll ← PRINCIPAL     │  epoll_wait() aqui!\n│    (I/O: rede, pipes)     │  Bloqueia até evento ou timer\n├───────────────────────────┤\n│    ⑤ Check                │  setImmediate() callbacks\n│    (pós-poll)             │\n├───────────────────────────┤\n│    ⑥ Close                │  socket.on(\'close\')\n│    (cleanup)              │  Libera recursos\n└───────────────────────────┘\n    ↻ process.nextTick() e Microtasks (Promises)\n      executam ENTRE cada fase!</div><p><strong>process.nextTick()</strong> vs <strong>setImmediate()</strong>: nextTick executa <em>antes</em> de qualquer fase (entre fases), com prioridade absoluta — pode causar starvation se usado recursivamente. setImmediate executa na fase Check, após o Poll. Para I/O callbacks, setImmediate sempre dispara antes de setTimeout(fn, 0).</p><p>A beleza do epoll é que ele escala com <strong>O(1)</strong> — monitorar 1 fd ou 100.000 fds custa o mesmo. O kernel mantém uma estrutura eficiente (red-black tree) e notifica apenas os fds com eventos pendentes. Isso permite que um único processo Node.js gerencie dezenas de milhares de conexões simultâneas.</p>',
      refs: [
        {text: 'Event Loop Phases (Node.js Docs)', url: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick'},
        {text: 'man 7 epoll (Linux)', url: 'https://man7.org/linux/man-pages/man7/epoll.7.html'},
        {text: 'libuv Design Overview', url: 'https://docs.libuv.org/en/v1.x/design.html'}
      ]
    },
    {
      short: '3. accept4() e V8',
      title: '📥 Accept e os Bindings V8: Conectando C++ ao JavaScript',
      content: '<p>Quando um cliente completa o 3-Way Handshake, o kernel move a conexão da SYN Queue para a <strong>Accept Queue</strong>. O epoll_wait retorna, sinalizando que o fd do servidor está "readable". A libuv então executa a syscall <span class="highlight">accept4()</span>:</p><div class="code-block">// accept4 = accept + flags atômicos (Linux-específico)\nint client_fd = accept4(server_fd=3, &addr, &addrlen, \n                        SOCK_NONBLOCK | SOCK_CLOEXEC);\n→ client_fd = 16\n\n// SOCK_NONBLOCK: O fd do cliente já nasce non-blocking\n//   (read/write retornam EAGAIN em vez de bloquear)\n// SOCK_CLOEXEC:  fd é fechado automaticamente em exec()\n//   (segurança: child processes não herdam o socket)\n\n// O kernel retorna:\n// • client_fd = 16 (novo File Descriptor para esse cliente)\n// • addr = { IP: 192.168.1.100, Port: 52431 } (quem conectou)</div><p>Agora a libuv precisa "acordar" o JavaScript. É aqui que entra a <strong>ponte C++ ↔ JS</strong> via V8 Internals:</p><ul><li><strong>V8 Isolate:</strong> Uma instância isolada do engine V8, com seu próprio Heap (memória gerenciada pelo GC). Cada processo Node.js tem exatamente 1 Isolate na main thread.</li><li><strong>HandleScope:</strong> Escopo que gerencia referências a objetos JS no lado C++. Ao sair do escopo, referências são liberadas automaticamente.</li><li><strong>TCPWrap / StreamWrap:</strong> Classes C++ que "envolvem" o fd e implementam a interface de streams do Node. Registram callbacks JS para eventos.</li></ul><div class="code-block">// Fluxo interno (simplificado):\n1. libuv detecta evento no epoll    (C, kernel)\n2. uv__server_io() é chamado         (C, libuv)\n3. TCPWrap::OnConnection() é chamado  (C++, Node bindings)\n4. MakeCallback(onconnection, args)   (C++ → V8 bridge)\n5. O V8 executa seu callback JS:      (JavaScript)\n   server.on(\'connection\', (socket) => { ... })\n6. O objeto \'socket\' JS refere-se ao client_fd=16 via TCPWrap</div><p>Todo esse caminho — do hardware interrupt à placa de rede, passando pelo kernel (epoll), libuv (C), bindings C++, e finalmente ao seu callback JavaScript — acontece em <strong>microssegundos</strong>. É essa engenharia em camadas que permite ao Node.js ser tão eficiente com uma única thread.</p>',
      refs: [
        {text: 'TCPWrap Source (Node.js)', url: 'https://github.com/nodejs/node/blob/main/src/tcp_wrap.cc'},
        {text: 'V8 Embedder\'s Guide', url: 'https://v8.dev/docs/embed'}
      ]
    },
    {
      short: '4. Thread Pool (libuv)',
      title: '🏊 Thread Pool: O Segredo Multi-Thread do Node',
      content: '<p>"Node.js é single-threaded" é uma <strong>meia-verdade</strong>. A main thread (Event Loop) é única, sim. Mas a libuv mantém um <span class="highlight">Thread Pool</span> de workers para operações que <em>não possuem APIs assíncronas no kernel</em> — ou seja, operações que bloqueariam a main thread.</p><div class="code-block">// Tamanho padrão: 4 threads\n// Configurável via variável de ambiente:\nUV_THREADPOOL_SIZE=16 node server.js   // Máximo: 1024\n\n// Operações que vão para o Thread Pool:\n┌──────────────────────────────────────┐\n│  fs.*  (read, write, stat, readdir)  │  ← I/O de disco\n│  dns.lookup()                        │  ← Resolução DNS via getaddrinfo()\n│  crypto.pbkdf2(), randomBytes()      │  ← Criptografia CPU-intensiva\n│  zlib.deflate(), gzip()              │  ← Compressão\n│  Qualquer uv_queue_work() customizado│\n└──────────────────────────────────────┘\n\n// Operações que NÃO usam Thread Pool (usam epoll direto):\n┌──────────────────────────────────────┐\n│  net.* (TCP sockets)                 │  ← epoll/kqueue\n│  http.* / https.*                    │  ← epoll via libuv\n│  dns.resolve() / dns.resolve4()      │  ← c-ares (async DNS)\n│  Pipes, TTY, UDP                     │  ← epoll/kqueue\n│  child_process (signals)             │  ← epoll\n└──────────────────────────────────────┘</div><p>O fluxo de uma operação no Thread Pool:</p><ul><li><strong>1.</strong> <code>fs.readFile()</code> no JS envia um "work request" para a fila do thread pool.</li><li><strong>2.</strong> Uma worker thread pega o request e executa a syscall bloqueante (<code>read()</code>) — ela pode bloquear sem problemas, pois não é a main thread.</li><li><strong>3.</strong> Ao terminar, a worker sinaliza via <code>uv_async_send()</code> que o resultado está pronto.</li><li><strong>4.</strong> O Event Loop (na próxima iteração do Poll) pega o resultado e executa o callback JS na main thread.</li></ul><p><strong>Armadilha:</strong> Com apenas 4 threads padrão, se 4 operações <code>fs.readFile()</code> grandes rodarem simultaneamente, uma 5ª fica na fila esperando. Isso pode causar latência inesperada em aplicações com muito I/O de disco. Solução: aumentar <code>UV_THREADPOOL_SIZE</code> ou usar APIs de streaming (<code>fs.createReadStream()</code>) que processam em chunks.</p><p>Note que <code>dns.lookup()</code> (que usa <code>getaddrinfo</code> POSIX, bloqueante) vai para o Thread Pool, mas <code>dns.resolve4()</code> (que usa a biblioteca <strong>c-ares</strong>, assíncrona) não. Para alta concorrência de DNS, prefira <code>dns.resolve*()</code>.</p>',
      refs: [
        {text: 'libuv Thread Pool (Docs)', url: 'https://docs.libuv.org/en/v1.x/threadpool.html'},
        {text: 'Don\'t Block the Event Loop (Node.js)', url: 'https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop'}
      ]
    },
    {
      short: '5. read() e Buffers',
      title: '💾 Memória Off-Heap: Buffers e Zero-Copy',
      content: '<p>Os bytes da requisição HTTP chegaram ao fd do cliente. Agora o Node precisa <em>ler</em> esses dados. A libuv dispara a syscall <code>read()</code> que copia bytes do <strong>Kernel Space</strong> para o <strong>User Space</strong>:</p><div class="code-block">// O kernel mantém um buffer interno (sk_buff) para cada socket\n// read() copia os dados do kernel para a memória do processo\n\nssize_t n = read(client_fd=16, buffer, 65536);\n→ n = 478 bytes lidos\n→ buffer contém: "GET /api/users HTTP/1.1\\r\\nHost: ..."</div><p>Esses bytes poderiam ir direto para uma string JavaScript no Heap do V8. Mas o Heap do V8 tem limites e é gerenciado pelo <strong>Garbage Collector (GC)</strong>:</p><ul><li>Heap máximo padrão: <strong>~1.4GB</strong> (sistemas 32-bit) a <strong>~4GB</strong> (64-bit, ajustável com <code>--max-old-space-size</code>).</li><li>O GC do V8 (Orinoco) tem pausas de <em>stop-the-world</em> durante compactação — quanto mais lixo no Heap, maiores as pausas.</li><li>Copiar buffers de rede para strings JS criaria pressão enorme no GC sob alta carga.</li></ul><p>A solução é o <span class="highlight">Buffer</span> — uma classe que aloca memória <strong>fora do Heap V8</strong>, diretamente via <code>malloc()</code> da libc:</p><div class="code-block">// Buffer.alloc(size) → Aloca e zera a memória (seguro)\n// Buffer.allocUnsafe(size) → Aloca sem zerar (rápido, pode ter lixo)\n// Buffer.from(data) → Cria a partir de string/array\n\n// Internamente, Buffers pequenos (< 8KB) usam o Slab Allocator:\n// Um "slab" de 8KB é pré-alocado e compartilhado entre múltiplos Buffers\n\nSlab (8192 bytes):\n┌──buf1(128B)──┬──buf2(256B)──┬──buf3(64B)──┬──livre────────┐\n│ dados HTTP   │ header resp  │ cookie      │ ...           │\n└──────────────┴──────────────┴─────────────┴───────────────┘\n\n// Buffers grandes (≥ 8KB) recebem alocação dedicada via malloc()</div><p>Como a memória do Buffer vive fora do Heap V8, o GC não precisa rastreá-la. O buffer é liberado quando o objeto JavaScript que o referencia é coletado — via weak reference e destrutor C++.</p><p>Em cenários de alto throughput, técnicas de <strong>zero-copy</strong> como <code>sendfile()</code> permitem transferir dados diretamente do fd de disco para o fd de socket <em>sem nunca copiar para o user space</em> — o kernel faz a transferência internamente via DMA (Direct Memory Access), eliminando cópias redundantes.</p>',
      refs: [
        {text: 'Buffer (Node.js Docs)', url: 'https://nodejs.org/api/buffer.html'},
        {text: 'V8 Garbage Collector (Orinoco)', url: 'https://v8.dev/blog/trash-talk'}
      ]
    },
    {
      short: '6. llhttp (Parser HTTP)',
      title: '🧠 llhttp: O Parser HTTP como Máquina de Estados',
      content: '<p>Os bytes brutos no Buffer são uma string como <code>"GET /home HTTP/1.1\\r\\nHost: ex.com\\r\\n\\r\\n"</code>. Transformar isso em um objeto JavaScript estruturado (<code>req.method</code>, <code>req.url</code>, <code>req.headers</code>) poderia ser feito com RegExp ou <code>string.split()</code> — mas isso consumiria <strong>milhões de ciclos de CPU</strong> em operações caras de busca e alocação de strings.</p><p>Em vez disso, o Node.js usa o <span class="highlight">llhttp</span> — um parser HTTP escrito em <strong>C</strong> que funciona como uma <strong>FSM (Finite State Machine)</strong>. Cada byte é lido sequencialmente, e o parser transita entre estados internos sem criar strings intermediárias:</p><div class="code-block">Fluxo do llhttp (simplificado):\n\nByte a byte: "G" → "E" → "T" → " " → "/" → "h" → "o" → "m" → "e" → " "\n\nEstados da FSM:\n┌─────────────────┐\n│ s_req_method     │ "G","E","T" → detecta method=GET\n├─────────────────┤\n│ s_req_url        │ "/","h","o","m","e" → captura url=/home\n├─────────────────┤\n│ s_req_http_ver   │ "H","T","T","P","/","1",".","1" → version=1.1\n├─────────────────┤\n│ s_header_field   │ "H","o","s","t" → header key = "Host"\n├─────────────────┤\n│ s_header_value   │ "e","x",".","c","o","m" → header val = "ex.com"\n├─────────────────┤\n│ s_headers_done   │ "\\r\\n\\r\\n" → dispara callback!\n├─────────────────┤\n│ s_body           │ (se Content-Length > 0) → lê N bytes do body\n└─────────────────┘</div><p>A cada transição relevante, o llhttp dispara <strong>callbacks</strong> para o Node.js:</p><ul><li><code>on_message_begin</code> — Início de uma nova mensagem HTTP.</li><li><code>on_url</code> — URL completa parseada (sem alocação de string até aqui!).</li><li><code>on_header_field</code> / <code>on_header_value</code> — Cada par header:valor, entregue separadamente.</li><li><code>on_headers_complete</code> — Todos os headers foram lidos. O Node monta o objeto <code>req.headers</code> neste ponto.</li><li><code>on_body</code> — Chunk do body recebido (para requests POST/PUT).</li><li><code>on_message_complete</code> — Mensagem inteira processada. Dispara o callback do seu <code>server.on(\'request\')</code>.</li></ul><p>O llhttp é gerado automaticamente a partir de uma definição em <strong>TypeScript</strong> (llparse), compilada para C otimizado. Essa abordagem combina a legibilidade do TypeScript com a performance bruta do C. O resultado: parsing de ~3GB/s em hardware moderno, ordens de magnitude mais rápido que qualquer parser JavaScript.</p><p><strong>HTTP Keep-Alive:</strong> Após processar uma mensagem, o parser volta ao estado inicial e reutiliza o mesmo socket para a próxima request, evitando o custo de novo handshake TCP. O header <code>Connection: keep-alive</code> (padrão em HTTP/1.1) permite que dezenas de requests trafeguem pela mesma conexão.</p>',
      refs: [
        {text: 'llhttp (Repositório GitHub)', url: 'https://github.com/nodejs/llhttp'},
        {text: 'HTTP Parser Performance (Benchmark)', url: 'https://github.com/nicolo-ribaudo/llhttp#performance'}
      ]
    },
    {
      short: '7. Response e Streams',
      title: '📤 Response: Streams, Backpressure e a Volta ao Fio',
      content: '<p>Após seu código JavaScript processar a request e chamar <code>res.end(body)</code>, os dados precisam fazer o caminho inverso — do User Space, pelo kernel, até a placa de rede. Esse processo envolve <strong>Writable Streams</strong> e o mecanismo crítico de <span class="highlight">Backpressure</span>.</p><div class="code-block">// res.writeHead() → monta os headers HTTP de resposta\n// res.write(chunk) → envia chunk para o socket (pode ser chamado N vezes)\n// res.end(body) → envia dados finais + sinaliza fim da resposta\n\n// Internamente:\nres.end("Hello World");\n  → StreamWrap::WriteUtf8String()      (C++ binding)\n    → uv_write(req, handle, bufs, cb)  (libuv)\n      → write(fd=16, buffer, length)   (syscall kernel)\n        → TCP enfileira no send buffer → placa de rede → fio</div><p><strong>Chunked Transfer-Encoding:</strong> Quando o Node não sabe o tamanho total da resposta antecipadamente (streaming, geração dinâmica), ele usa <code>Transfer-Encoding: chunked</code>. Cada <code>res.write()</code> envia um chunk com seu tamanho prefixado em hexadecimal, finalizando com um chunk de tamanho 0:</p><div class="code-block">HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n\nb\r\n             ← 0xb = 11 bytes\nHello World\r\n\n0\r\n\r\n          ← chunk final (tamanho 0 = fim)</div><p><strong>Backpressure</strong> é o mecanismo que evita overflow quando o produtor (seu código) gera dados mais rápido que o consumidor (rede/cliente) consegue absorver:</p><ul><li><code>res.write(chunk)</code> retorna <strong>false</strong> se o buffer interno do socket estiver cheio (highWaterMark, padrão 16KB).</li><li>Seu código deve <strong>parar de escrever</strong> e aguardar o evento <code>\'drain\'</code>, que indica que o buffer esvaziou o suficiente.</li><li>Sem respeitar backpressure, os dados se acumulam na memória → crash por OOM (Out of Memory).</li><li><code>stream.pipe()</code> e <code>pipeline()</code> gerenciam backpressure automaticamente.</li></ul><p>O <strong>TCP Nagle\'s Algorithm</strong> (habilitado por padrão) agrupa pequenas escritas em um único segmento TCP para reduzir overhead de headers. Para aplicações de baixa latência (jogos, streaming), desabilite com <code>socket.setNoDelay(true)</code> que ativa <code>TCP_NODELAY</code>, enviando cada write imediatamente.</p><p>Ao chamar <code>res.end()</code>, o Node envia um <strong>FIN</strong> no TCP, iniciando o half-close. O cliente recebe o FIN, envia ACK de volta, e eventualmente também envia seu FIN — completando o 4-Way Termination e liberando o fd do socket.</p>',
      refs: [
        {text: 'Stream (Node.js Docs)', url: 'https://nodejs.org/api/stream.html'},
        {text: 'Backpressure in Streams', url: 'https://nodejs.org/en/learn/modules/backpressuring-in-streams'},
        {text: 'Nagle\'s Algorithm', url: 'https://en.wikipedia.org/wiki/Nagle%27s_algorithm'}
      ]
    }
  ]
};
